package com.kmplibs.asciidoc.integration

import kotlin.test.Test
import kotlin.test.Ignore

class SectionsTest {

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `synthetic id is generated by default`() {
        // Input: asciidoctor/sections_test_synthetic_id_is_generated_by_default.adoc
        // Expected: sectionsTestSyntheticIdIsGeneratedByDefault
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `synthetic id removes non-word characters`() {
        // Input: asciidoctor/sections_test_synthetic_id_removes_non_word_characters.adoc
        // Expected: sectionsTestSyntheticIdRemovesNonWordCharacters
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `synthetic id separator can be set to blank`() {
        // Input: asciidoctor/sections_test_synthetic_id_separator_can_be_set_to_blank.adoc
        // Expected: sectionsTestSyntheticIdSeparatorCanBeSetToBlank
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `explicit id can be defined using an embedded anchor`() {
        // Input: asciidoctor/sections_test_explicit_id_can_be_defined_using_an_embedded_anchor.adoc
        // Expected: sectionsTestExplicitIdCanBeDefinedUsingAnEmbeddedAnchor
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should apply substitutions to title with attribute references when registering section with auto-generated ID`() {
        // Input: asciidoctor/sections_test_should_apply_substitutions_to_title_with_attribute_references_when_registering_section_with_auto_generated_id.adoc
        // Expected: sectionsTestShouldApplySubstitutionsToTitleWithAttributeReferencesWhenRegisteringSectionWithAutoGeneratedId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should apply substitutions to title with attribute references when registering section with explicit ID`() {
        // Input: asciidoctor/sections_test_should_apply_substitutions_to_title_with_attribute_references_when_registering_section_with_explicit_id.adoc
        // Expected: sectionsTestShouldApplySubstitutionsToTitleWithAttributeReferencesWhenRegisteringSectionWithExplicitId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not apply substitutions to title with attribute references when parsing section with empty ID`() {
        // Input: asciidoctor/sections_test_should_not_apply_substitutions_to_title_with_attribute_references_when_parsing_section_with_empty_id.adoc
        // Expected: sectionsTestShouldNotApplySubstitutionsToTitleWithAttributeReferencesWhenParsingSectionWithEmptyId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `title substitutions are applied before generating id`() {
        // Input: asciidoctor/sections_test_title_substitutions_are_applied_before_generating_id.adoc
        // Expected: sectionsTestTitleSubstitutionsAreAppliedBeforeGeneratingId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `can set start index of synthetic ids`() {
        // Input: asciidoctor/sections_test_can_set_start_index_of_synthetic_ids.adoc
        // Expected: sectionsTestCanSetStartIndexOfSyntheticIds
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use specified id and reftext when registering section reference`() {
        // Input: asciidoctor/sections_test_should_use_specified_id_and_reftext_when_registering_section_reference.adoc
        // Expected: sectionsTestShouldUseSpecifiedIdAndReftextWhenRegisteringSectionReference
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use specified reftext when registering section reference`() {
        // Input: asciidoctor/sections_test_should_use_specified_reftext_when_registering_section_reference.adoc
        // Expected: sectionsTestShouldUseSpecifiedReftextWhenRegisteringSectionReference
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should resolve attribute reference in title using attribute defined at location of section title`() {
        // Input: asciidoctor/sections_test_should_resolve_attribute_reference_in_title_using_attribute_defined_at_location_of_section_title.adoc
        // Expected: sectionsTestShouldResolveAttributeReferenceInTitleUsingAttributeDefinedAtLocationOfSectionTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should substitute attributes when registering reftext for section`() {
        // Input: asciidoctor/sections_test_should_substitute_attributes_when_registering_reftext_for_section.adoc
        // Expected: sectionsTestShouldSubstituteAttributesWhenRegisteringReftextForSection
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `duplicate section id should not overwrite existing section id entry in references table`() {
        // Input: asciidoctor/sections_test_duplicate_section_id_should_not_overwrite_existing_section_id_entry_in_references_table.adoc
        // Expected: sectionsTestDuplicateSectionIdShouldNotOverwriteExistingSectionIdEntryInReferencesTable
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should warn if explicit section ID matches auto-generated section ID`() {
        // Input: asciidoctor/sections_test_should_warn_if_explicit_section_id_matches_auto_generated_section_id.adoc
        // Expected: sectionsTestShouldWarnIfExplicitSectionIdMatchesAutoGeneratedSectionId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `duplicate block id should not overwrite existing section id entry in references table`() {
        // Input: asciidoctor/sections_test_duplicate_block_id_should_not_overwrite_existing_section_id_entry_in_references_table.adoc
        // Expected: sectionsTestDuplicateBlockIdShouldNotOverwriteExistingSectionIdEntryInReferencesTable
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `document title with multiline syntax`() {
        // Input: asciidoctor/sections_test_document_title_with_multiline_syntax.adoc
        // Expected: sectionsTestDocumentTitleWithMultilineSyntax
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `not enough chars for a multiline document title`() {
        // Input: asciidoctor/sections_test_not_enough_chars_for_a_multiline_document_title.adoc
        // Expected: sectionsTestNotEnoughCharsForAMultilineDocumentTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should assign id defined using shorthand syntax on document title to body`() {
        // Input: asciidoctor/sections_test_should_assign_id_defined_using_shorthand_syntax_on_document_title_to_body.adoc
        // Expected: sectionsTestShouldAssignIdDefinedUsingShorthandSyntaxOnDocumentTitleToBody
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use ID defined in block attributes instead of ID defined inline`() {
        // Input: asciidoctor/sections_test_should_use_id_defined_in_block_attributes_instead_of_id_defined_inline.adoc
        // Expected: sectionsTestShouldUseIdDefinedInBlockAttributesInsteadOfIdDefinedInline
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `block id above document title sets id on document`() {
        // Input: asciidoctor/sections_test_block_id_above_document_title_sets_id_on_document.adoc
        // Expected: sectionsTestBlockIdAboveDocumentTitleSetsIdOnDocument
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should register document in catalog if id is set`() {
        // Input: asciidoctor/sections_test_should_register_document_in_catalog_if_id_is_set.adoc
        // Expected: sectionsTestShouldRegisterDocumentInCatalogIfIdIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should compute xreftext to document title`() {
        // Input: asciidoctor/sections_test_should_compute_xreftext_to_document_title.adoc
        // Expected: sectionsTestShouldComputeXreftextToDocumentTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not interpret level-0 section as document title if it has a style`() {
        // Input: asciidoctor/sections_test_should_not_interpret_level_0_section_as_document_title_if_it_has_a_style.adoc
        // Expected: sectionsTestShouldNotInterpretLevel0SectionAsDocumentTitleIfItHasAStyle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should discard role and options shorthand attributes defined on document title`() {
        // Input: asciidoctor/sections_test_should_discard_role_and_options_shorthand_attributes_defined_on_document_title.adoc
        // Expected: sectionsTestShouldDiscardRoleAndOptionsShorthandAttributesDefinedOnDocumentTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `with multiline syntax`() {
        // Input: asciidoctor/sections_test_with_multiline_syntax.adoc
        // Expected: sectionsTestWithMultilineSyntax
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not recognize section title that does not contain alphanumeric character`() {
        // Input: asciidoctor/sections_test_should_not_recognize_section_title_that_does_not_contain_alphanumeric_character.adoc
        // Expected: sectionsTestShouldNotRecognizeSectionTitleThatDoesNotContainAlphanumericCharacter
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not recognize section title that consists of only underscores`() {
        // Input: asciidoctor/sections_test_should_not_recognize_section_title_that_consists_of_only_underscores.adoc
        // Expected: sectionsTestShouldNotRecognizeSectionTitleThatConsistsOfOnlyUnderscores
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should preprocess second line of setext section title`() {
        // Input: asciidoctor/sections_test_should_preprocess_second_line_of_setext_section_title.adoc
        // Expected: sectionsTestShouldPreprocessSecondLineOfSetextSectionTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `heading title with multiline syntax cannot begin with a dot`() {
        // Input: asciidoctor/sections_test_heading_title_with_multiline_syntax_cannot_begin_with_a_dot.adoc
        // Expected: sectionsTestHeadingTitleWithMultilineSyntaxCannotBeginWithADot
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should warn if section title is out of sequence`() {
        // Input: asciidoctor/sections_test_should_warn_if_section_title_is_out_of_sequence.adoc
        // Expected: sectionsTestShouldWarnIfSectionTitleIsOutOfSequence
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should warn if chapter title is out of sequence`() {
        // Input: asciidoctor/sections_test_should_warn_if_chapter_title_is_out_of_sequence.adoc
        // Expected: sectionsTestShouldWarnIfChapterTitleIsOutOfSequence
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not warn if top-level section title is out of sequence when fragment attribute is set on document`() {
        // Input: asciidoctor/sections_test_should_not_warn_if_top_level_section_title_is_out_of_sequence_when_fragment_attribute_is_set_on_document.adoc
        // Expected: sectionsTestShouldNotWarnIfTopLevelSectionTitleIsOutOfSequenceWhenFragmentAttributeIsSetOnDocument
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should warn if nested section title is out of sequence when fragment attribute is set on document`() {
        // Input: asciidoctor/sections_test_should_warn_if_nested_section_title_is_out_of_sequence_when_fragment_attribute_is_set_on_document.adoc
        // Expected: sectionsTestShouldWarnIfNestedSectionTitleIsOutOfSequenceWhenFragmentAttributeIsSetOnDocument
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should log error if subsections are found in special sections in article that do not support subsections`() {
        // Input: asciidoctor/sections_test_should_log_error_if_subsections_are_found_in_special_sections_in_article_that_do_not_support_subsections.adoc
        // Expected: sectionsTestShouldLogErrorIfSubsectionsAreFoundInSpecialSectionsInArticleThatDoNotSupportSubsections
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should log error if subsections are found in special sections in book that do not support subsections`() {
        // Input: asciidoctor/sections_test_should_log_error_if_subsections_are_found_in_special_sections_in_book_that_do_not_support_subsections.adoc
        // Expected: sectionsTestShouldLogErrorIfSubsectionsAreFoundInSpecialSectionsInBookThatDoNotSupportSubsections
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `atx document title with leading marker`() {
        // Input: asciidoctor/sections_test_atx_document_title_with_leading_marker.adoc
        // Expected: sectionsTestAtxDocumentTitleWithLeadingMarker
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `atx section title with symmetric markers`() {
        // Input: asciidoctor/sections_test_atx_section_title_with_symmetric_markers.adoc
        // Expected: sectionsTestAtxSectionTitleWithSymmetricMarkers
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should create discrete heading instead of section if style is float`() {
        // Input: asciidoctor/sections_test_should_create_discrete_heading_instead_of_section_if_style_is_float.adoc
        // Expected: sectionsTestShouldCreateDiscreteHeadingInsteadOfSectionIfStyleIsFloat
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should create discrete heading instead of section if style is discrete`() {
        // Input: asciidoctor/sections_test_should_create_discrete_heading_instead_of_section_if_style_is_discrete.adoc
        // Expected: sectionsTestShouldCreateDiscreteHeadingInsteadOfSectionIfStyleIsDiscrete
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should generate id for discrete heading from converted title`() {
        // Input: asciidoctor/sections_test_should_generate_id_for_discrete_heading_from_converted_title.adoc
        // Expected: sectionsTestShouldGenerateIdForDiscreteHeadingFromConvertedTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should create discrete heading if style is float with shorthand role and id`() {
        // Input: asciidoctor/sections_test_should_create_discrete_heading_if_style_is_float_with_shorthand_role_and_id.adoc
        // Expected: sectionsTestShouldCreateDiscreteHeadingIfStyleIsFloatWithShorthandRoleAndId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should create discrete heading if style is discrete with shorthand role and id`() {
        // Input: asciidoctor/sections_test_should_create_discrete_heading_if_style_is_discrete_with_shorthand_role_and_id.adoc
        // Expected: sectionsTestShouldCreateDiscreteHeadingIfStyleIsDiscreteWithShorthandRoleAndId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `discrete heading should be a block with context floating_title`() {
        // Input: asciidoctor/sections_test_discrete_heading_should_be_a_block_with_context_floating_title.adoc
        // Expected: sectionsTestDiscreteHeadingShouldBeABlockWithContextFloatingTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should preprocess second line of setext discrete heading`() {
        // Input: asciidoctor/sections_test_should_preprocess_second_line_of_setext_discrete_heading.adoc
        // Expected: sectionsTestShouldPreprocessSecondLineOfSetextDiscreteHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `can assign explicit id to discrete heading`() {
        // Input: asciidoctor/sections_test_can_assign_explicit_id_to_discrete_heading.adoc
        // Expected: sectionsTestCanAssignExplicitIdToDiscreteHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not include discrete heading in toc`() {
        // Input: asciidoctor/sections_test_should_not_include_discrete_heading_in_toc.adoc
        // Expected: sectionsTestShouldNotIncludeDiscreteHeadingInToc
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not set id on discrete heading if sectids attribute is unset`() {
        // Input: asciidoctor/sections_test_should_not_set_id_on_discrete_heading_if_sectids_attribute_is_unset.adoc
        // Expected: sectionsTestShouldNotSetIdOnDiscreteHeadingIfSectidsAttributeIsUnset
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use explicit id for discrete heading if specified`() {
        // Input: asciidoctor/sections_test_should_use_explicit_id_for_discrete_heading_if_specified.adoc
        // Expected: sectionsTestShouldUseExplicitIdForDiscreteHeadingIfSpecified
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should add role to class attribute on discrete heading`() {
        // Input: asciidoctor/sections_test_should_add_role_to_class_attribute_on_discrete_heading.adoc
        // Expected: sectionsTestShouldAddRoleToClassAttributeOnDiscreteHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should ignore title attribute on discrete heading`() {
        // Input: asciidoctor/sections_test_should_ignore_title_attribute_on_discrete_heading.adoc
        // Expected: sectionsTestShouldIgnoreTitleAttributeOnDiscreteHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use specified id and reftext when registering discrete section reference`() {
        // Input: asciidoctor/sections_test_should_use_specified_id_and_reftext_when_registering_discrete_section_reference.adoc
        // Expected: sectionsTestShouldUseSpecifiedIdAndReftextWhenRegisteringDiscreteSectionReference
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use specified reftext when registering discrete section reference`() {
        // Input: asciidoctor/sections_test_should_use_specified_reftext_when_registering_discrete_section_reference.adoc
        // Expected: sectionsTestShouldUseSpecifiedReftextWhenRegisteringDiscreteSectionReference
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not process inline anchor in discrete heading if explicit ID is assigned`() {
        // Input: asciidoctor/sections_test_should_not_process_inline_anchor_in_discrete_heading_if_explicit_id_is_assigned.adoc
        // Expected: sectionsTestShouldNotProcessInlineAnchorInDiscreteHeadingIfExplicitIdIsAssigned
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should print error if standalone document is included without level offset`() {
        // Input: asciidoctor/sections_test_should_print_error_if_standalone_document_is_included_without_level_offset.adoc
        // Expected: sectionsTestShouldPrintErrorIfStandaloneDocumentIsIncludedWithoutLevelOffset
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should add level offset to section level`() {
        // Input: asciidoctor/sections_test_should_add_level_offset_to_section_level.adoc
        // Expected: sectionsTestShouldAddLevelOffsetToSectionLevel
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `level offset should be added to discrete heading`() {
        // Input: asciidoctor/sections_test_level_offset_should_be_added_to_discrete_heading.adoc
        // Expected: sectionsTestLevelOffsetShouldBeAddedToDiscreteHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should be able to reset level offset`() {
        // Input: asciidoctor/sections_test_should_be_able_to_reset_level_offset.adoc
        // Expected: sectionsTestShouldBeAbleToResetLevelOffset
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should add relative offset value to current leveloffset`() {
        // Input: asciidoctor/sections_test_should_add_relative_offset_value_to_current_leveloffset.adoc
        // Expected: sectionsTestShouldAddRelativeOffsetValueToCurrentLeveloffset
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output section numbers when sectnums attribute is set`() {
        // Input: asciidoctor/sections_test_should_output_section_numbers_when_sectnums_attribute_is_set.adoc
        // Expected: sectionsTestShouldOutputSectionNumbersWhenSectnumsAttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output section numbers when numbered attribute is set`() {
        // Input: asciidoctor/sections_test_should_output_section_numbers_when_numbered_attribute_is_set.adoc
        // Expected: sectionsTestShouldOutputSectionNumbersWhenNumberedAttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not crash if child section of part is out of sequence and part numbering is disabled`() {
        // Input: asciidoctor/sections_test_should_not_crash_if_child_section_of_part_is_out_of_sequence_and_part_numbering_is_disabled.adoc
        // Expected: sectionsTestShouldNotCrashIfChildSectionOfPartIsOutOfSequenceAndPartNumberingIsDisabled
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not hang if relative leveloffset attempts to make resolved section level negative`() {
        // Input: asciidoctor/sections_test_should_not_hang_if_relative_leveloffset_attempts_to_make_resolved_section_level_negative.adoc
        // Expected: sectionsTestShouldNotHangIfRelativeLeveloffsetAttemptsToMakeResolvedSectionLevelNegative
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should number parts when doctype is book and partnums attributes is set`() {
        // Input: asciidoctor/sections_test_should_number_parts_when_doctype_is_book_and_partnums_attributes_is_set.adoc
        // Expected: sectionsTestShouldNumberPartsWhenDoctypeIsBookAndPartnumsAttributesIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should assign sequential roman numerals to book parts`() {
        // Input: asciidoctor/sections_test_should_assign_sequential_roman_numerals_to_book_parts.adoc
        // Expected: sectionsTestShouldAssignSequentialRomanNumeralsToBookParts
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should prepend value of part-signifier attribute to title of numbered part`() {
        // Input: asciidoctor/sections_test_should_prepend_value_of_part_signifier_attribute_to_title_of_numbered_part.adoc
        // Expected: sectionsTestShouldPrependValueOfPartSignifierAttributeToTitleOfNumberedPart
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should prepend value of chapter-signifier attribute to title of numbered chapter`() {
        // Input: asciidoctor/sections_test_should_prepend_value_of_chapter_signifier_attribute_to_title_of_numbered_chapter.adoc
        // Expected: sectionsTestShouldPrependValueOfChapterSignifierAttributeToTitleOfNumberedChapter
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should allow chapter number to be controlled using chapter-number attribute`() {
        // Input: asciidoctor/sections_test_should_allow_chapter_number_to_be_controlled_using_chapter_number_attribute.adoc
        // Expected: sectionsTestShouldAllowChapterNumberToBeControlledUsingChapterNumberAttribute
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `blocks should have level`() {
        // Input: asciidoctor/sections_test_blocks_should_have_level.adoc
        // Expected: sectionsTestBlocksShouldHaveLevel
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `section numbers should not increment when numbered attribute is turned off within document`() {
        // Input: asciidoctor/sections_test_section_numbers_should_not_increment_when_numbered_attribute_is_turned_off_within_document.adoc
        // Expected: sectionsTestSectionNumbersShouldNotIncrementWhenNumberedAttributeIsTurnedOffWithinDocument
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `section numbers can be toggled even if numbered attribute is enable via the API`() {
        // Input: asciidoctor/sections_test_section_numbers_can_be_toggled_even_if_numbered_attribute_is_enable_via_the_api.adoc
        // Expected: sectionsTestSectionNumbersCanBeToggledEvenIfNumberedAttributeIsEnableViaTheApi
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `section numbers cannot be toggled even if numbered attribute is disabled via the API`() {
        // Input: asciidoctor/sections_test_section_numbers_cannot_be_toggled_even_if_numbered_attribute_is_disabled_via_the_api.adoc
        // Expected: sectionsTestSectionNumbersCannotBeToggledEvenIfNumberedAttributeIsDisabledViaTheApi
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `section numbers should not increment until numbered attribute is turned back on`() {
        // Input: asciidoctor/sections_test_section_numbers_should_not_increment_until_numbered_attribute_is_turned_back_on.adoc
        // Expected: sectionsTestSectionNumbersShouldNotIncrementUntilNumberedAttributeIsTurnedBackOn
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `table with asciidoc content should not disable numbering of subsequent sections`() {
        // Input: asciidoctor/sections_test_table_with_asciidoc_content_should_not_disable_numbering_of_subsequent_sections.adoc
        // Expected: sectionsTestTableWithAsciidocContentShouldNotDisableNumberingOfSubsequentSections
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not number parts when doctype is book`() {
        // Input: asciidoctor/sections_test_should_not_number_parts_when_doctype_is_book.adoc
        // Expected: sectionsTestShouldNotNumberPartsWhenDoctypeIsBook
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should number chapters sequentially even when divided into parts`() {
        // Input: asciidoctor/sections_test_should_number_chapters_sequentially_even_when_divided_into_parts.adoc
        // Expected: sectionsTestShouldNumberChaptersSequentiallyEvenWhenDividedIntoParts
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `reindex_sections should correct section enumeration after sections are modified`() {
        // Input: asciidoctor/sections_test_reindex_sections_should_correct_section_enumeration_after_sections_are_modified.adoc
        // Expected: sectionsTestReindexSectionsShouldCorrectSectionEnumerationAfterSectionsAreModified
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should allow sections to be renumbered using numeral or deprecated number property`() {
        // Input: asciidoctor/sections_test_should_allow_sections_to_be_renumbered_using_numeral_or_deprecated_number_property.adoc
        // Expected: sectionsTestShouldAllowSectionsToBeRenumberedUsingNumeralOrDeprecatedNumberProperty
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should include anchor if sectanchors document attribute is set`() {
        // Input: asciidoctor/sections_test_should_include_anchor_if_sectanchors_document_attribute_is_set.adoc
        // Expected: sectionsTestShouldIncludeAnchorIfSectanchorsDocumentAttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should position after title text if sectanchors is set to after`() {
        // Input: asciidoctor/sections_test_should_position_after_title_text_if_sectanchors_is_set_to_after.adoc
        // Expected: sectionsTestShouldPositionAfterTitleTextIfSectanchorsIsSetToAfter
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should link section if sectlinks document attribute is set`() {
        // Input: asciidoctor/sections_test_should_link_section_if_sectlinks_document_attribute_is_set.adoc
        // Expected: sectionsTestShouldLinkSectionIfSectlinksDocumentAttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should ignore style if it matches sectN`() {
        // Input: asciidoctor/sections_test_should_ignore_style_if_it_matches_sect_n.adoc
        // Expected: sectionsTestShouldIgnoreStyleIfItMatchesSectN
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should assign sectname, caption, and numeral to appendix section by default`() {
        // Input: asciidoctor/sections_test_should_assign_sectname_caption_and_numeral_to_appendix_section_by_default.adoc
        // Expected: sectionsTestShouldAssignSectnameCaptionAndNumeralToAppendixSectionByDefault
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not promote level-0 special section in book doctype to document title`() {
        // Input: asciidoctor/sections_test_should_not_promote_level_0_special_section_in_book_doctype_to_document_title.adoc
        // Expected: sectionsTestShouldNotPromoteLevel0SpecialSectionInBookDoctypeToDocumentTitle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should prefix appendix title by numbered label even when section numbering is disabled`() {
        // Input: asciidoctor/sections_test_should_prefix_appendix_title_by_numbered_label_even_when_section_numbering_is_disabled.adoc
        // Expected: sectionsTestShouldPrefixAppendixTitleByNumberedLabelEvenWhenSectionNumberingIsDisabled
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should allow appendix number to be controlled using appendix-number attribute`() {
        // Input: asciidoctor/sections_test_should_allow_appendix_number_to_be_controlled_using_appendix_number_attribute.adoc
        // Expected: sectionsTestShouldAllowAppendixNumberToBeControlledUsingAppendixNumberAttribute
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use style from last block attribute line above section that defines a style`() {
        // Input: asciidoctor/sections_test_should_use_style_from_last_block_attribute_line_above_section_that_defines_a_style.adoc
        // Expected: sectionsTestShouldUseStyleFromLastBlockAttributeLineAboveSectionThatDefinesAStyle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `setting ID using style shorthand should not clear section style`() {
        // Input: asciidoctor/sections_test_setting_id_using_style_shorthand_should_not_clear_section_style.adoc
        // Expected: sectionsTestSettingIdUsingStyleShorthandShouldNotClearSectionStyle
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use custom appendix caption if specified`() {
        // Input: asciidoctor/sections_test_should_use_custom_appendix_caption_if_specified.adoc
        // Expected: sectionsTestShouldUseCustomAppendixCaptionIfSpecified
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should only assign letter to appendix when numbered is enabled and appendix caption is not set`() {
        // Input: asciidoctor/sections_test_should_only_assign_letter_to_appendix_when_numbered_is_enabled_and_appendix_caption_is_not_set.adoc
        // Expected: sectionsTestShouldOnlyAssignLetterToAppendixWhenNumberedIsEnabledAndAppendixCaptionIsNotSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should increment appendix number for each appendix section`() {
        // Input: asciidoctor/sections_test_should_increment_appendix_number_for_each_appendix_section.adoc
        // Expected: sectionsTestShouldIncrementAppendixNumberForEachAppendixSection
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should continue numbering after appendix`() {
        // Input: asciidoctor/sections_test_should_continue_numbering_after_appendix.adoc
        // Expected: sectionsTestShouldContinueNumberingAfterAppendix
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should number appendix subsections using appendix letter`() {
        // Input: asciidoctor/sections_test_should_number_appendix_subsections_using_appendix_letter.adoc
        // Expected: sectionsTestShouldNumberAppendixSubsectionsUsingAppendixLetter
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not number level 4 section by default`() {
        // Input: asciidoctor/sections_test_should_not_number_level_4_section_by_default.adoc
        // Expected: sectionsTestShouldNotNumberLevel4SectionByDefault
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should only number levels up to value defined by sectnumlevels attribute`() {
        // Input: asciidoctor/sections_test_should_only_number_levels_up_to_value_defined_by_sectnumlevels_attribute.adoc
        // Expected: sectionsTestShouldOnlyNumberLevelsUpToValueDefinedBySectnumlevelsAttribute
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not number sections or subsections in regions where numbered is off`() {
        // Input: asciidoctor/sections_test_should_not_number_sections_or_subsections_in_regions_where_numbered_is_off.adoc
        // Expected: sectionsTestShouldNotNumberSectionsOrSubsectionsInRegionsWhereNumberedIsOff
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not number sections or subsections in toc in regions where numbered is off`() {
        // Input: asciidoctor/sections_test_should_not_number_sections_or_subsections_in_toc_in_regions_where_numbered_is_off.adoc
        // Expected: sectionsTestShouldNotNumberSectionsOrSubsectionsInTocInRegionsWhereNumberedIsOff
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should only number sections in toc up to value defined by sectnumlevels attribute`() {
        // Input: asciidoctor/sections_test_should_only_number_sections_in_toc_up_to_value_defined_by_sectnumlevels_attribute.adoc
        // Expected: sectionsTestShouldOnlyNumberSectionsInTocUpToValueDefinedBySectnumlevelsAttribute
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not number special sections or their subsections by default except for appendices`() {
        // Input: asciidoctor/sections_test_should_not_number_special_sections_or_their_subsections_by_default_except_for_appendices.adoc
        // Expected: sectionsTestShouldNotNumberSpecialSectionsOrTheirSubsectionsByDefaultExceptForAppendices
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not number special sections or their subsections in toc by default except for appendices`() {
        // Input: asciidoctor/sections_test_should_not_number_special_sections_or_their_subsections_in_toc_by_default_except_for_appendices.adoc
        // Expected: sectionsTestShouldNotNumberSpecialSectionsOrTheirSubsectionsInTocByDefaultExceptForAppendices
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should number special sections and their subsections when sectnums is all`() {
        // Input: asciidoctor/sections_test_should_number_special_sections_and_their_subsections_when_sectnums_is_all.adoc
        // Expected: sectionsTestShouldNumberSpecialSectionsAndTheirSubsectionsWhenSectnumsIsAll
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should number special sections and their subsections in toc when sectnums is all`() {
        // Input: asciidoctor/sections_test_should_number_special_sections_and_their_subsections_in_toc_when_sectnums_is_all.adoc
        // Expected: sectionsTestShouldNumberSpecialSectionsAndTheirSubsectionsInTocWhenSectnumsIsAll
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `level 0 special sections in multipart book should be coerced to level 1`() {
        // Input: asciidoctor/sections_test_level_0_special_sections_in_multipart_book_should_be_coerced_to_level_1.adoc
        // Expected: sectionsTestLevel0SpecialSectionsInMultipartBookShouldBeCoercedToLevel1
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output docbook elements that correspond to special sections in book doctype`() {
        // Input: asciidoctor/sections_test_should_output_docbook_elements_that_correspond_to_special_sections_in_book_doctype.adoc
        // Expected: sectionsTestShouldOutputDocbookElementsThatCorrespondToSpecialSectionsInBookDoctype
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `abstract section maps to abstract element in docbook for article doctype`() {
        // Input: asciidoctor/sections_test_abstract_section_maps_to_abstract_element_in_docbook_for_article_doctype.adoc
        // Expected: sectionsTestAbstractSectionMapsToAbstractElementInDocbookForArticleDoctype
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should allow a special section to be nested at arbitrary depth in DocBook output`() {
        // Input: asciidoctor/sections_test_should_allow_a_special_section_to_be_nested_at_arbitrary_depth_in_doc_book_output.adoc
        // Expected: sectionsTestShouldAllowASpecialSectionToBeNestedAtArbitraryDepthInDocBookOutput
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not interpret a listing block as a heading`() {
        // Input: asciidoctor/sections_test_should_not_interpret_a_listing_block_as_a_heading.adoc
        // Expected: sectionsTestShouldNotInterpretAListingBlockAsAHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not interpret an open block as a heading`() {
        // Input: asciidoctor/sections_test_should_not_interpret_an_open_block_as_a_heading.adoc
        // Expected: sectionsTestShouldNotInterpretAnOpenBlockAsAHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not interpret an attribute list as a heading`() {
        // Input: asciidoctor/sections_test_should_not_interpret_an_attribute_list_as_a_heading.adoc
        // Expected: sectionsTestShouldNotInterpretAnAttributeListAsAHeading
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not match a heading in a description list`() {
        // Input: asciidoctor/sections_test_should_not_match_a_heading_in_a_description_list.adoc
        // Expected: sectionsTestShouldNotMatchAHeadingInADescriptionList
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not match a heading in a bulleted list`() {
        // Input: asciidoctor/sections_test_should_not_match_a_heading_in_a_bulleted_list.adoc
        // Expected: sectionsTestShouldNotMatchAHeadingInABulletedList
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not match a heading in a block`() {
        // Input: asciidoctor/sections_test_should_not_match_a_heading_in_a_block.adoc
        // Expected: sectionsTestShouldNotMatchAHeadingInABlock
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output unnumbered table of contents in header if toc attribute is set`() {
        // Input: asciidoctor/sections_test_should_output_unnumbered_table_of_contents_in_header_if_toc_attribute_is_set.adoc
        // Expected: sectionsTestShouldOutputUnnumberedTableOfContentsInHeaderIfTocAttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output numbered table of contents in header if toc and numbered attributes are set`() {
        // Input: asciidoctor/sections_test_should_output_numbered_table_of_contents_in_header_if_toc_and_numbered_attributes_are_set.adoc
        // Expected: sectionsTestShouldOutputNumberedTableOfContentsInHeaderIfTocAndNumberedAttributesAreSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output a table of contents that honors numbered setting at position of section in document`() {
        // Input: asciidoctor/sections_test_should_output_a_table_of_contents_that_honors_numbered_setting_at_position_of_section_in_document.adoc
        // Expected: sectionsTestShouldOutputATableOfContentsThatHonorsNumberedSettingAtPositionOfSectionInDocument
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not number parts in table of contents for book doctype when numbered attribute is set`() {
        // Input: asciidoctor/sections_test_should_not_number_parts_in_table_of_contents_for_book_doctype_when_numbered_attribute_is_set.adoc
        // Expected: sectionsTestShouldNotNumberPartsInTableOfContentsForBookDoctypeWhenNumberedAttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output table of contents in header if toc2 attribute is set`() {
        // Input: asciidoctor/sections_test_should_output_table_of_contents_in_header_if_toc_2_attribute_is_set.adoc
        // Expected: sectionsTestShouldOutputTableOfContentsInHeaderIfToc2AttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should set toc position if toc attribute is set to position`() {
        // Input: asciidoctor/sections_test_should_set_toc_position_if_toc_attribute_is_set_to_position.adoc
        // Expected: sectionsTestShouldSetTocPositionIfTocAttributeIsSetToPosition
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should set toc position if toc and toc-position attributes are set`() {
        // Input: asciidoctor/sections_test_should_set_toc_position_if_toc_and_toc_position_attributes_are_set.adoc
        // Expected: sectionsTestShouldSetTocPositionIfTocAndTocPositionAttributesAreSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should set toc position if toc2 and toc-position attribute are set`() {
        // Input: asciidoctor/sections_test_should_set_toc_position_if_toc_2_and_toc_position_attribute_are_set.adoc
        // Expected: sectionsTestShouldSetTocPositionIfToc2AndTocPositionAttributeAreSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should set toc position if toc attribute is set to direction`() {
        // Input: asciidoctor/sections_test_should_set_toc_position_if_toc_attribute_is_set_to_direction.adoc
        // Expected: sectionsTestShouldSetTocPositionIfTocAttributeIsSetToDirection
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should set toc placement to preamble if toc attribute is set to preamble`() {
        // Input: asciidoctor/sections_test_should_set_toc_placement_to_preamble_if_toc_attribute_is_set_to_preamble.adoc
        // Expected: sectionsTestShouldSetTocPlacementToPreambleIfTocAttributeIsSetToPreamble
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use document attributes toc-class, toc-title and toclevels to create toc`() {
        // Input: asciidoctor/sections_test_should_use_document_attributes_toc_class_toc_title_and_toclevels_to_create_toc.adoc
        // Expected: sectionsTestShouldUseDocumentAttributesTocClassTocTitleAndToclevelsToCreateToc
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not output table of contents if toc-placement attribute is unset`() {
        // Input: asciidoctor/sections_test_should_not_output_table_of_contents_if_toc_placement_attribute_is_unset.adoc
        // Expected: sectionsTestShouldNotOutputTableOfContentsIfTocPlacementAttributeIsUnset
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output table of contents at location of toc macro`() {
        // Input: asciidoctor/sections_test_should_output_table_of_contents_at_location_of_toc_macro.adoc
        // Expected: sectionsTestShouldOutputTableOfContentsAtLocationOfTocMacro
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output table of contents at location of toc macro in embedded document`() {
        // Input: asciidoctor/sections_test_should_output_table_of_contents_at_location_of_toc_macro_in_embedded_document.adoc
        // Expected: sectionsTestShouldOutputTableOfContentsAtLocationOfTocMacroInEmbeddedDocument
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should output table of contents at default location in embedded document if toc attribute is set`() {
        // Input: asciidoctor/sections_test_should_output_table_of_contents_at_default_location_in_embedded_document_if_toc_attribute_is_set.adoc
        // Expected: sectionsTestShouldOutputTableOfContentsAtDefaultLocationInEmbeddedDocumentIfTocAttributeIsSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not activate toc macro if toc-placement is not set`() {
        // Input: asciidoctor/sections_test_should_not_activate_toc_macro_if_toc_placement_is_not_set.adoc
        // Expected: sectionsTestShouldNotActivateTocMacroIfTocPlacementIsNotSet
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should only output toc at toc macro if toc is macro`() {
        // Input: asciidoctor/sections_test_should_only_output_toc_at_toc_macro_if_toc_is_macro.adoc
        // Expected: sectionsTestShouldOnlyOutputTocAtTocMacroIfTocIsMacro
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should use global attributes for toc-title, toc-class and toclevels for toc macro`() {
        // Input: asciidoctor/sections_test_should_use_global_attributes_for_toc_title_toc_class_and_toclevels_for_toc_macro.adoc
        // Expected: sectionsTestShouldUseGlobalAttributesForTocTitleTocClassAndToclevelsForTocMacro
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should honor id, title, role and level attributes on toc macro`() {
        // Input: asciidoctor/sections_test_should_honor_id_title_role_and_level_attributes_on_toc_macro.adoc
        // Expected: sectionsTestShouldHonorIdTitleRoleAndLevelAttributesOnTocMacro
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `child toc levels should not have additional bullet at parent level in html`() {
        // Input: asciidoctor/sections_test_child_toc_levels_should_not_have_additional_bullet_at_parent_level_in_html.adoc
        // Expected: sectionsTestChildTocLevelsShouldNotHaveAdditionalBulletAtParentLevelInHtml
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not display a table of contents if document has no sections`() {
        // Input: asciidoctor/sections_test_should_not_display_a_table_of_contents_if_document_has_no_sections.adoc
        // Expected: sectionsTestShouldNotDisplayATableOfContentsIfDocumentHasNoSections
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should drop anchors from contents of entries in table of contents`() {
        // Input: asciidoctor/sections_test_should_drop_anchors_from_contents_of_entries_in_table_of_contents.adoc
        // Expected: sectionsTestShouldDropAnchorsFromContentsOfEntriesInTableOfContents
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not remove non-anchor tags from contents of entries in table of contents`() {
        // Input: asciidoctor/sections_test_should_not_remove_non_anchor_tags_from_contents_of_entries_in_table_of_contents.adoc
        // Expected: sectionsTestShouldNotRemoveNonAnchorTagsFromContentsOfEntriesInTableOfContents
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should create only sections in docbook backend`() {
        // Input: asciidoctor/sections_test_should_create_only_sections_in_docbook_backend.adoc
        // Expected: sectionsTestShouldCreateOnlySectionsInDocbookBackend
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `document title with level 0 headings`() {
        // Input: asciidoctor/sections_test_document_title_with_level_0_headings.adoc
        // Expected: sectionsTestDocumentTitleWithLevel0Headings
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should print error if level 0 section comes after nested section and doctype is not book`() {
        // Input: asciidoctor/sections_test_should_print_error_if_level_0_section_comes_after_nested_section_and_doctype_is_not_book.adoc
        // Expected: sectionsTestShouldPrintErrorIfLevel0SectionComesAfterNestedSectionAndDoctypeIsNotBook
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should add class matching role to part`() {
        // Input: asciidoctor/sections_test_should_add_class_matching_role_to_part.adoc
        // Expected: sectionsTestShouldAddClassMatchingRoleToPart
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should assign appropriate sectname for section type`() {
        // Input: asciidoctor/sections_test_should_assign_appropriate_sectname_for_section_type.adoc
        // Expected: sectionsTestShouldAssignAppropriateSectnameForSectionType
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should allow part intro to be defined using special section`() {
        // Input: asciidoctor/sections_test_should_allow_part_intro_to_be_defined_using_special_section.adoc
        // Expected: sectionsTestShouldAllowPartIntroToBeDefinedUsingSpecialSection
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should add partintro style to child paragraph of part`() {
        // Input: asciidoctor/sections_test_should_add_partintro_style_to_child_paragraph_of_part.adoc
        // Expected: sectionsTestShouldAddPartintroStyleToChildParagraphOfPart
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should preserve title on partintro defined as partintro paragraph`() {
        // Input: asciidoctor/sections_test_should_preserve_title_on_partintro_defined_as_partintro_paragraph.adoc
        // Expected: sectionsTestShouldPreserveTitleOnPartintroDefinedAsPartintroParagraph
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not promote title on partintro defined as normal paragraph`() {
        // Input: asciidoctor/sections_test_should_not_promote_title_on_partintro_defined_as_normal_paragraph.adoc
        // Expected: sectionsTestShouldNotPromoteTitleOnPartintroDefinedAsNormalParagraph
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should add partintro style to child open block of part`() {
        // Input: asciidoctor/sections_test_should_add_partintro_style_to_child_open_block_of_part.adoc
        // Expected: sectionsTestShouldAddPartintroStyleToChildOpenBlockOfPart
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should wrap child paragraphs of part in partintro open block`() {
        // Input: asciidoctor/sections_test_should_wrap_child_paragraphs_of_part_in_partintro_open_block.adoc
        // Expected: sectionsTestShouldWrapChildParagraphsOfPartInPartintroOpenBlock
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should wrap abstract in implicit part intro in info tag when converting to DocBook`() {
        // Input: asciidoctor/sections_test_should_wrap_abstract_in_implicit_part_intro_in_info_tag_when_converting_to_doc_book.adoc
        // Expected: sectionsTestShouldWrapAbstractInImplicitPartIntroInInfoTagWhenConvertingToDocBook
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should wrap abstract in part intro section in info tag when converting to DocBook`() {
        // Input: asciidoctor/sections_test_should_wrap_abstract_in_part_intro_section_in_info_tag_when_converting_to_doc_book.adoc
        // Expected: sectionsTestShouldWrapAbstractInPartIntroSectionInInfoTagWhenConvertingToDocBook
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should warn if part has no sections`() {
        // Input: asciidoctor/sections_test_should_warn_if_part_has_no_sections.adoc
        // Expected: sectionsTestShouldWarnIfPartHasNoSections
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should create parts and chapters in docbook backend`() {
        // Input: asciidoctor/sections_test_should_create_parts_and_chapters_in_docbook_backend.adoc
        // Expected: sectionsTestShouldCreatePartsAndChaptersInDocbookBackend
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `subsections in preface and appendix should start at level 2`() {
        // Input: asciidoctor/sections_test_subsections_in_preface_and_appendix_should_start_at_level_2.adoc
        // Expected: sectionsTestSubsectionsInPrefaceAndAppendixShouldStartAtLevel2
    }

}
