package com.kmplibs.asciidoc.integration

import kotlin.test.Test
import kotlin.test.Ignore

class SubstitutionsTest {

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `an externalized footnote macro may contain text formatting`() {
        // Input: asciidoctor/substitutions_test_an_externalized_footnote_macro_may_contain_text_formatting.adoc
        // Expected: substitutionsTestAnExternalizedFootnoteMacroMayContainTextFormatting
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `using a footnoteref macro should generate a warning when compat mode is not enabled`() {
        // Input: asciidoctor/substitutions_test_using_a_footnoteref_macro_should_generate_a_warning_when_compat_mode_is_not_enabled.adoc
        // Expected: substitutionsTestUsingAFootnoterefMacroShouldGenerateAWarningWhenCompatModeIsNotEnabled
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should parse multiple footnote references in a single line`() {
        // Input: asciidoctor/substitutions_test_should_parse_multiple_footnote_references_in_a_single_line.adoc
        // Expected: substitutionsTestShouldParseMultipleFootnoteReferencesInASingleLine
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should not resolve an inline footnote macro missing both id and text`() {
        // Input: asciidoctor/substitutions_test_should_not_resolve_an_inline_footnote_macro_missing_both_id_and_text.adoc
        // Expected: substitutionsTestShouldNotResolveAnInlineFootnoteMacroMissingBothIdAndText
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `inline footnote macro can define a numeric id without conflicting with auto-generated ID`() {
        // Input: asciidoctor/substitutions_test_inline_footnote_macro_can_define_a_numeric_id_without_conflicting_with_auto_generated_id.adoc
        // Expected: substitutionsTestInlineFootnoteMacroCanDefineANumericIdWithoutConflictingWithAutoGeneratedId
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should be able to reference a bibliography entry in a footnote`() {
        // Input: asciidoctor/substitutions_test_should_be_able_to_reference_a_bibliography_entry_in_a_footnote.adoc
        // Expected: substitutionsTestShouldBeAbleToReferenceABibliographyEntryInAFootnote
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `footnotes in headings are expected to be numbered out of sequence`() {
        // Input: asciidoctor/substitutions_test_footnotes_in_headings_are_expected_to_be_numbered_out_of_sequence.adoc
        // Expected: substitutionsTestFootnotesInHeadingsAreExpectedToBeNumberedOutOfSequence
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `a single-line index term macro with a primary term should be registered as an index reference`() {
        // Input: asciidoctor/substitutions_test_a_single_line_index_term_macro_with_a_primary_term_should_be_registered_as_an_index_reference.adoc
        // Expected: substitutionsTestASingleLineIndexTermMacroWithAPrimaryTermShouldBeRegisteredAsAnIndexReference
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `registers multiple index term macros`() {
        // Input: asciidoctor/substitutions_test_registers_multiple_index_term_macros.adoc
        // Expected: substitutionsTestRegistersMultipleIndexTermMacros
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `visible shorthand index term macro should not consume leading round bracket`() {
        // Input: asciidoctor/substitutions_test_visible_shorthand_index_term_macro_should_not_consume_leading_round_bracket.adoc
        // Expected: substitutionsTestVisibleShorthandIndexTermMacroShouldNotConsumeLeadingRoundBracket
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `index term 2 macro with round bracket syntex should not interfer with index term macro with round bracket syntax`() {
        // Input: asciidoctor/substitutions_test_index_term_2_macro_with_round_bracket_syntex_should_not_interfer_with_index_term_macro_with_round_bracket_syntax.adoc
        // Expected: substitutionsTestIndexTerm2MacroWithRoundBracketSyntexShouldNotInterferWithIndexTermMacroWithRoundBracketSyntax
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should parse concealed shorthand index term with see and seealso`() {
        // Input: asciidoctor/substitutions_test_should_parse_concealed_shorthand_index_term_with_see_and_seealso.adoc
        // Expected: substitutionsTestShouldParseConcealedShorthandIndexTermWithSeeAndSeealso
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should parse visible index term macro with see and seealso`() {
        // Input: asciidoctor/substitutions_test_should_parse_visible_index_term_macro_with_see_and_seealso.adoc
        // Expected: substitutionsTestShouldParseVisibleIndexTermMacroWithSeeAndSeealso
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `should parse concealed index term macro with see and seealso`() {
        // Input: asciidoctor/substitutions_test_should_parse_concealed_index_term_macro_with_see_and_seealso.adoc
        // Expected: substitutionsTestShouldParseConcealedIndexTermMacroWithSeeAndSeealso
    }

    @Test
    @Ignore // TODO: Implement AST comparison
    fun `replaces dashes`() {
        // Input: asciidoctor/substitutions_test_replaces_dashes.adoc
        // Expected: substitutionsTestReplacesDashes
    }

}
